# Generated by Django 4.2.23 on 2025-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0006_archive_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveddemand",
            name="quantityplanned",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="planned quantity",
            ),
        ),
    ]
