# Generated by Django 4.2.23 on 2026-02-21 22:58

from django.db import migrations, models
import django.utils.timezone
import freppledb.labels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('template', models.FileField(upload_to='svg/', validators=[freppledb.labels.models.LabelTemplate.validate_svg])),
            ],
            options={
                'verbose_name': 'Шаблон этикетки',
                'verbose_name_plural': 'Шаблоны этикеток',
                'db_table': 'labels',
                'abstract': False,
            },
        ),
    ]
