# Generated by Django 4.2.23 on 2026-02-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_labeltemplate_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='dir',
            field=models.CharField(default='', max_length=300, verbose_name='directory'),
        ),
    ]
