# Generated by Django 4.2.23 on 2026-02-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_labeltemplate_dir'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labeltemplate',
            table='lb_labels',
        ),
    ]
