# Generated by Django 4.2.23 on 2026-02-28 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_labeltemplate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('file', models.FileField(upload_to='created_labels/')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('dir', models.CharField(default='', max_length=300, verbose_name='directory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.labeltemplate')),
            ],
            options={
                'verbose_name': 'Созданная этикетка',
                'verbose_name_plural': 'Созданные этикетки',
                'db_table': 'lb_createdlabels',
                'abstract': False,
            },
        ),
    ]
