# Generated by Django 4.2.23 on 2025-07-21 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="My_Model",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="name"
                    ),
                ),
                (
                    "charfield",
                    models.CharField(
                        blank=True,
                        help_text="A sample character field",
                        null=True,
                        verbose_name="charfield",
                    ),
                ),
                (
                    "booleanfield",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="A sample boolean field",
                        verbose_name="booleanfield",
                    ),
                ),
                (
                    "decimalfield",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="A sample decimal field",
                        max_digits=5,
                        verbose_name="decimalfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "my model",
                "verbose_name_plural": "my models",
                "db_table": "my_model",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
