# Generated by Django 4.2.23 on 2025-07-21 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0085_alter_item_latedemandcount_and_more"),
        ("technology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CutList",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="name"
                    ),
                ),
                (
                    "hanged_no",
                    models.CharField(
                        blank=True,
                        help_text="Номер на вешале",
                        max_length=20,
                        null=True,
                        verbose_name="hanged_no",
                    ),
                ),
                (
                    "SP_pos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default="",
                        help_text="№ позиции в спецификации или сборочном чертеже",
                        max_digits=3,
                        verbose_name="Позиция в СП",
                    ),
                ),
                (
                    "wire_no",
                    models.CharField(
                        help_text="Имя жилы или провода",
                        max_length=20,
                        verbose_name="имя провода",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="количество"
                    ),
                ),
                (
                    "start_strip",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        verbose_name="Зачистка начало, мм",
                    ),
                ),
                (
                    "start_tinning",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="лужение начала провода",
                        verbose_name="облудить начало",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="длина"
                    ),
                ),
                (
                    "end_tinning",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="лужение конец провода",
                        verbose_name="облудить конец",
                    ),
                ),
                (
                    "end_strip",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        verbose_name="Зачистка конец, мм",
                    ),
                ),
                (
                    "allowance",
                    models.DecimalField(
                        decimal_places=8,
                        default="0",
                        max_digits=20,
                        verbose_name="припуск",
                    ),
                ),
                (
                    "soldering",
                    models.BooleanField(
                        default=False,
                        help_text="пайка проводов",
                        verbose_name="пайка проводов",
                    ),
                ),
                (
                    "end_tip",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_tip_in_cutlists",
                        to="input.item",
                        verbose_name="наконечник конца провода",
                    ),
                ),
                (
                    "from_seal",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_seal_in_cutlists",
                        to="input.item",
                        verbose_name="уплотнитель начала провода",
                    ),
                ),
                (
                    "from_tip",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_tip_in_cutlists",
                        to="input.item",
                        verbose_name="наконечник начала провода",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutlists",
                        to="input.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "to_seal",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_seal_in_cutlists",
                        to="input.item",
                        verbose_name="уплотнитель конец провода",
                    ),
                ),
            ],
            options={
                "verbose_name": "my model",
                "verbose_name_plural": "my models",
                "db_table": "my_model",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="My_Model",
        ),
    ]
