# Generated by Django 4.2.23 on 2025-07-21 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0002_cutlist_delete_my_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cutlist",
            options={
                "ordering": ["SP_pos"],
                "verbose_name": "cut list",
                "verbose_name_plural": "cut lists",
            },
        ),
        migrations.AlterModelTable(
            name="cutlist",
            table="cut_list",
        ),
    ]
