# Generated by Django 4.2.23 on 2026-02-22 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0281_alter_item_latedemandcount_and_more'),
        ('codescan', '0002_barcode_lastusedqr_qr_workstation_and_more'),
        ('technology', '0002_connectionlist_itemt_mobilehanger_solderingscheme_and_more'),
    ]

    operations = [

    ]
