# Generated by Django 4.2.23 on 2025-07-21 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0003_alter_cutlist_options_alter_cutlist_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CutList",
        ),
    ]
