# Generated by Django 4.2.23 on 2026-02-22 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codescan', '0002_barcode_lastusedqr_qr_workstation_and_more'),
        ('technology', '0003_connectionlist_itemt_mobilehanger_solderingscheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionList',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('hanged_no', models.CharField(blank=True, help_text='Номер крючка на вешале', max_length=20, null=True, verbose_name='№ на вешале')),
                ('qr', models.CharField(blank=True, null=True, verbose_name='mQR')),
                ('SP_pos', models.DecimalField(blank=True, decimal_places=0, default='', help_text='№ позиции в спецификации или сборочном чертеже', max_digits=3, null=True, verbose_name='Позиция в СП')),
                ('wire_no', models.CharField(help_text='Имя жилы или провода', max_length=20, verbose_name='имя провода')),
                ('sygnal', models.CharField(blank=True, help_text='Имя цепи', max_length=20, null=True, verbose_name='имя цепи')),
                ('quantity', models.DecimalField(decimal_places=0, default='', max_digits=20, verbose_name='количество')),
                ('from_connector', models.CharField(blank=True, help_text='от разъёма', max_length=20, null=True, verbose_name='от разъёма')),
                ('from_pin', models.DecimalField(blank=True, decimal_places=0, help_text='от контакта', max_digits=3, null=True, verbose_name='от контакта')),
                ('start_strip', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Зачистка начало, мм')),
                ('start_tinning', models.BooleanField(blank=True, default=False, help_text='лужение начала провода', verbose_name='облудить начало')),
                ('length', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='длина')),
                ('to_connector', models.CharField(blank=True, help_text='к разъёму', max_length=20, null=True, verbose_name='к разъёму')),
                ('to_pin', models.DecimalField(blank=True, decimal_places=0, help_text='к контакту', max_digits=3, null=True, verbose_name='к контакту')),
                ('end_tinning', models.BooleanField(blank=True, default=False, help_text='лужение конец провода', verbose_name='облудить конец')),
                ('end_strip', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Зачистка конец, мм')),
                ('allowance', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=5, null=True, verbose_name='припуск')),
                ('soldering', models.BooleanField(default=False, help_text='пайка проводов', verbose_name='пайка проводов')),
            ],
            options={
                'verbose_name': 'Таблица соединений',
                'verbose_name_plural': 'Таблицы соединений',
                'db_table': 'connection_list',
                'ordering': ['SP_pos'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemT',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='input.item')),
                ('image', models.ImageField(blank=True, default=None, height_field='image_height', null=True, upload_to='img/', width_field='image_width')),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('imagef', models.ImageField(blank=True, default=None, height_field='imagef_height', null=True, upload_to='img/', width_field='imagef_width')),
                ('imagef_height', models.IntegerField(blank=True, null=True)),
                ('imagef_width', models.IntegerField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, null=True, verbose_name='арт.')),
                ('erp_code', models.CharField(blank=True, null=True, verbose_name='erp code')),
                ('barcode_number', models.CharField(blank=True, null=True, verbose_name='Номер штрих-кода')),
                ('barcode', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barcode_owners', to='codescan.barcode', verbose_name='Штрих код')),
                ('opposite_item', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opposite_items', to='technology.itemt', verbose_name='Ответная часть')),
                ('qr', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_owners', to='codescan.qr', verbose_name='QR код')),
            ],
            options={
                'abstract': False,
            },
            bases=('input.item',),
        ),
        migrations.CreateModel(
            name='MobileHanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('number', models.CharField(verbose_name='Номер')),
                ('current_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tied_hangers', to='technology.itemt')),
            ],
            options={
                'verbose_name': 'Мобильное вешало',
                'verbose_name_plural': 'Мобильные вешала',
                'db_table': 'hangers',
                'ordering': ['number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolderingScheme',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('image', models.ImageField(blank=True, default='img/no_scheme.png', height_field='image_height', null=True, upload_to='img/', width_field='image_width')),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_soldering_scheme', to='technology.itemt', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Схема пайки',
                'verbose_name_plural': 'Схемы пайки',
                'db_table': 'solderingscheme',
                'ordering': ['item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('wire_no', models.CharField(help_text='Имя жилы или провода', max_length=20, verbose_name='имя провода')),
                ('image', models.ImageField(blank=True, default=None, height_field='image_height', null=True, upload_to='img/', width_field='image_width')),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trace_schemes', to='technology.itemt')),
            ],
            options={
                'verbose_name': 'Схема трассировки',
                'verbose_name_plural': 'Схемы трассировки',
                'db_table': 'trace_list',
                'ordering': ['item'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='My_Model',
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='from_seal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_seal_in_cutlists', to='technology.itemt', verbose_name='уплотнитель начала провода'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='from_tip',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_tip_in_cutlists', to='technology.itemt', verbose_name='наконечник начала провода'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='item',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_cutlists', to='technology.itemt', verbose_name='провод'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='operation',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='operation_cutlists', to='input.operation', verbose_name='операция'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='to_seal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_seal_in_cutlists', to='technology.itemt', verbose_name='уплотнитель конец провода'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='to_tip',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_tip_in_cutlists', to='technology.itemt', verbose_name='наконечник конца провода'),
        ),
    ]
