# Generated by Django 4.2.23 on 2026-02-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_labeltemplate_table'),
        ('technology', '0004_connectionlist_itemt_mobilehanger_solderingscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemt',
            name='passport_label_template',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_passports', to='labels.labeltemplate', verbose_name='Шаблон этикетки паспорта'),
        ),
    ]
