# Generated by Django 4.2.23 on 2025-07-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0005_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cutlist",
            old_name="end_tip",
            new_name="to_tip",
        ),
        migrations.AddField(
            model_name="cutlist",
            name="lft",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="cutlist",
            name="lvl",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cutlist",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Hierarchical parent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="xchildren",
                to="technology.cutlist",
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="cutlist",
            name="rght",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
