# Generated by Django 4.2.23 on 2026-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_itemt_passport_label_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilehanger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
