# Generated by Django 4.2.23 on 2025-07-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0093_alter_item_latedemandcount_and_more"),
        ("technology", "0006_rename_end_tip_cutlist_to_tip_cutlist_lft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="item",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cutlists",
                to="input.item",
                verbose_name="провод",
            ),
        ),
    ]
