# Generated by Django 4.2.23 on 2026-02-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_labeltemplate_table'),
        ('codescan', '0002_barcode_lastusedqr_qr_workstation_and_more'),
        ('technology', '0006_alter_mobilehanger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilehanger',
            name='label_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mobilehanger',
            name='label_template',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_hangers', to='labels.labeltemplate', verbose_name='Шаблон этикетки мобильного вешала'),
        ),
        migrations.AddField(
            model_name='mobilehanger',
            name='qr',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_mh_owners', to='codescan.qr', verbose_name='QR код'),
        ),
    ]
