# Generated by Django 4.2.23 on 2026-03-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0007_mobilehanger_label_path_mobilehanger_label_template_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connectionlist',
            table='technology_connection_list',
        ),
        migrations.AlterModelTable(
            name='mobilehanger',
            table='technology_hangers',
        ),
        migrations.AlterModelTable(
            name='solderingscheme',
            table='technology_solderingscheme',
        ),
        migrations.AlterModelTable(
            name='tracescheme',
            table='technology_trace_list',
        ),
    ]
