# Generated by Django 4.2.23 on 2025-07-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0007_alter_cutlist_item"),
    ]

    operations = [


    ]
