# Generated by Django 4.2.23 on 2026-03-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_createdlabel'),
        ('technology', '0008_alter_connectionlist_table_alter_mobilehanger_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilehanger',
            name='label',
            field=models.ForeignKey(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_hangers', to='labels.createdlabel', verbose_name='Этикетка'),
        ),
    ]
