# Generated by Django 4.2.23 on 2025-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0008_cutlist_id_alter_cutlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="name",
            field=models.CharField(
                help_text="Unique identifier",
                max_length=300,
                primary_key=False,
                serialize=False,
                verbose_name="name",
            ),
        ),
    ]
