# Generated by Django 4.2.23 on 2025-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0011_alter_cutlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutlist",
            name="name1",
            field=models.CharField(default="", verbose_name="name"),
            preserve_default=False,
        ),

    ]
