# Generated by Django 4.2.23 on 2025-07-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0012_cutlist_name1_alter_cutlist_name"),
    ]

    operations = [
        
    ]
