# Generated by Django 4.2.23 on 2025-07-23 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0013_remove_cutlist_name1_cutlist_id_alter_cutlist_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CutList",
        ),
    ]
