# Generated by Django 4.2.23 on 2025-07-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0104_alter_item_latedemandcount_and_more"),
        ("technology", "0015_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cutlist",
            options={
                "ordering": ["SP_pos"],
                "verbose_name": "Карта резки",
                "verbose_name_plural": "Карты резки",
            },
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="allowance",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default="0",
                max_digits=20,
                null=True,
                verbose_name="припуск",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="end_strip",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Зачистка конец, мм",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="from_seal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_seal_in_cutlists",
                to="input.item",
                verbose_name="уплотнитель начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="from_tip",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_tip_in_cutlists",
                to="input.item",
                verbose_name="наконечник начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="hanged_no",
            field=models.CharField(
                blank=True,
                help_text="Номер крючка на вешале",
                max_length=20,
                null=True,
                verbose_name="№ на вешале",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="start_strip",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Зачистка начало, мм",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_seal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_seal_in_cutlists",
                to="input.item",
                verbose_name="уплотнитель конец провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_tip",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_tip_in_cutlists",
                to="input.item",
                verbose_name="наконечник конца провода",
            ),
        ),
    ]
