# Generated by Django 4.2.23 on 2025-07-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0105_alter_item_latedemandcount_and_more"),
        ("technology", "0016_alter_cutlist_options_alter_cutlist_allowance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutlist",
            name="operation",
            field=models.ForeignKey(
                db_index=False,
                default="ПМА-4000.10.200 Жгут - Нарезка и зачистка проводов",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_cutlists",
                to="input.operation",
                verbose_name="операция",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="item",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_cutlists",
                to="input.item",
                verbose_name="провод",
            ),
        ),
    ]
