# Generated by Django 4.2.23 on 2025-07-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0018_mqrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutlist",
            name="mQR",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Микро QR",
                max_length=5,
                verbose_name="mQR",
            ),
        ),
    ]
