# Generated by Django 4.2.23 on 2025-07-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0019_cutlist_mqr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cutlist",
            name="mQR",
        ),
        migrations.AlterField(
            model_name="mqrcode",
            name="id",
            field=models.CharField(
                max_length=6,
                primary_key=True,
                serialize=False,
                verbose_name="identifier",
            ),
        ),
    ]
