# Generated by Django 4.2.23 on 2025-07-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0020_remove_cutlist_mqr_alter_mqrcode_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutlist",
            name="mQR2",
            field=models.CharField(
                blank=True, default="880000", help_text="Микро QR", verbose_name="mQR"
            ),
        ),
    ]
