# Generated by Django 4.2.23 on 2025-07-24 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0021_cutlist_mqr2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cutlist",
            old_name="mQR2",
            new_name="mQR",
        ),
    ]
