# Generated by Django 4.2.23 on 2025-07-24 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0022_rename_mqr2_cutlist_mqr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="mQRCode",
        ),
        migrations.RemoveField(
            model_name="cutlist",
            name="mQR",
        ),
    ]
