# Generated by Django 4.2.23 on 2025-07-24 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0023_delete_mqrcode_remove_cutlist_mqr"),
    ]

    operations = [
        migrations.CreateModel(
            name="mQRCode",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("0", "Оснастка"),
                            ("1", "Мобильное вешало"),
                            ("2", "Рабочее место"),
                            ("3", "Оборудование"),
                            ("4", "Мобильный стеллаж"),
                            ("5", "Стеллаж проводов"),
                            ("6", "Номенклатура"),
                            ("7", "Операция"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "mQR код",
                "verbose_name_plural": "mQR коды",
                "db_table": "m_qr_list",
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
