# Generated by Django 4.2.23 on 2025-07-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0025_cutlist_mqr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="SP_pos",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default="",
                help_text="№ позиции в спецификации или сборочном чертеже",
                max_digits=3,
                null=True,
                verbose_name="Позиция в СП",
            ),
        ),
    ]
