# Generated by Django 4.2.23 on 2025-07-25 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0026_alter_cutlist_sp_pos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cutlist",
            name="from_seal",
        ),
        migrations.RemoveField(
            model_name="cutlist",
            name="from_tip",
        ),
        migrations.RemoveField(
            model_name="cutlist",
            name="item",
        ),
        migrations.RemoveField(
            model_name="cutlist",
            name="operation",
        ),
        migrations.RemoveField(
            model_name="cutlist",
            name="to_seal",
        ),
        migrations.RemoveField(
            model_name="cutlist",
            name="to_tip",
        ),
        migrations.DeleteModel(
            name="mQRCode",
        ),
        migrations.DeleteModel(
            name="CutList",
        ),
    ]
