# Generated by Django 4.2.23 on 2025-07-25 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "technology",
            "0027_remove_cutlist_from_seal_remove_cutlist_from_tip_and_more",
        ),
    ]

    operations = []
