# Generated by Django 4.2.23 on 2025-07-26 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0029_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cutlist",
            name="mQR",
        ),
    ]
