# Generated by Django 4.2.23 on 2025-07-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0121_alter_item_latedemandcount_and_more"),
        ("technology", "0030_remove_cutlist_mqr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="from_seal",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_seal_in_cutlists",
                to="input.item",
                verbose_name="уплотнитель начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="from_tip",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_tip_in_cutlists",
                to="input.item",
                verbose_name="наконечник начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_seal",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_seal_in_cutlists",
                to="input.item",
                verbose_name="уплотнитель конец провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_tip",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_tip_in_cutlists",
                to="input.item",
                verbose_name="наконечник конца провода",
            ),
        ),
    ]
