# Generated by Django 4.2.23 on 2025-07-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0127_alter_item_latedemandcount_and_more"),
        ("technology", "0031_alter_cutlist_from_seal_alter_cutlist_from_tip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RichItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="input.item",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="image_height",
                        upload_to="img/",
                        width_field="image_width",
                    ),
                ),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("input.item",),
        ),
    ]
