# Generated by Django 4.2.23 on 2025-07-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0032_richitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="richitem",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="img/",
                width_field="image_width",
            ),
        ),
    ]
