# Generated by Django 4.2.23 on 2025-07-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0128_alter_item_latedemandcount_and_more"),
        ("technology", "0033_alter_richitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="richitem",
            name="short_name",
            field=models.CharField(blank=True, null=True, verbose_name="№ на вешале"),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="from_seal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_seal_in_cutlists",
                to="input.item",
                verbose_name="уплотнитель начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="from_tip",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_tip_in_cutlists",
                to="input.item",
                verbose_name="наконечник начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_seal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_seal_in_cutlists",
                to="input.item",
                verbose_name="уплотнитель конец провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_tip",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_tip_in_cutlists",
                to="input.item",
                verbose_name="наконечник конца провода",
            ),
        ),
    ]
