# Generated by Django 4.2.23 on 2025-07-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0129_alter_item_latedemandcount_and_more"),
        ("technology", "0034_richitem_short_name_alter_cutlist_from_seal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemT",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="input.item",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field="image_height",
                        null=True,
                        upload_to="img/",
                        width_field="image_width",
                    ),
                ),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                (
                    "short_name",
                    models.CharField(blank=True, null=True, verbose_name="арт."),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("input.item",),
        ),
        migrations.AddField(
            model_name="cutlist",
            name="qr",
            field=models.CharField(blank=True, null=True, verbose_name="mQR"),
        ),
        migrations.DeleteModel(
            name="RichItem",
        ),
    ]
