# Generated by Django 4.2.23 on 2025-07-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0035_itemt_cutlist_qr_delete_richitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="from_tip",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_tip_in_cutlists",
                to="technology.itemt",
                verbose_name="наконечник начала провода",
            ),
        ),
    ]
