# Generated by Django 4.2.23 on 2025-07-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0036_alter_cutlist_from_tip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="from_seal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_seal_in_cutlists",
                to="technology.itemt",
                verbose_name="уплотнитель начала провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="item",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_cutlists",
                to="technology.itemt",
                verbose_name="провод",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_seal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_seal_in_cutlists",
                to="technology.itemt",
                verbose_name="уплотнитель конец провода",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="to_tip",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_tip_in_cutlists",
                to="technology.itemt",
                verbose_name="наконечник конца провода",
            ),
        ),
    ]
