# Generated by Django 4.2.23 on 2025-07-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0037_alter_cutlist_from_seal_alter_cutlist_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemt",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="image_height",
                null=True,
                upload_to="img/",
                width_field="image_width",
            ),
        ),
    ]
