# Generated by Django 4.2.23 on 2025-08-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0038_alter_itemt_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemt",
            name="imagef",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="image_height",
                null=True,
                upload_to="img/",
                width_field="image_width",
            ),
        ),
        migrations.AddField(
            model_name="itemt",
            name="imagef_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemt",
            name="imagef_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
