# Generated by Django 4.2.23 on 2025-08-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0039_itemt_imagef_itemt_imagef_height_itemt_imagef_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemt",
            name="imagef",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="imagef_height",
                null=True,
                upload_to="img/",
                width_field="imagef_width",
            ),
        ),
    ]
