# Generated by Django 4.2.23 on 2025-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0040_alter_itemt_imagef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutlist",
            name="allowance",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default="0",
                max_digits=5,
                null=True,
                verbose_name="припуск",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="end_strip",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
                verbose_name="Зачистка конец, мм",
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="length",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="длина"
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="quantity",
            field=models.DecimalField(
                decimal_places=0, default="", max_digits=20, verbose_name="количество"
            ),
        ),
        migrations.AlterField(
            model_name="cutlist",
            name="start_strip",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
                verbose_name="Зачистка начало, мм",
            ),
        ),
    ]
