# Generated by Django 4.2.23 on 2025-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0041_alter_cutlist_allowance_alter_cutlist_end_strip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemt",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="img/",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="itemt",
            name="imagef",
            field=models.ImageField(
                blank=True,
                height_field="imagef_height",
                null=True,
                upload_to="img/",
                width_field="imagef_width",
            ),
        ),
    ]
