# Generated by Django 4.2.23 on 2025-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0042_alter_itemt_image_alter_itemt_imagef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemt",
            name="image",
            field=models.ImageField(
                blank=True,
                default="img/no_image.png",
                height_field="image_height",
                null=True,
                upload_to="img/",
                width_field="image_width",
            ),
        ),
    ]
