# Generated by Django 4.2.23 on 2025-08-10 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0043_alter_itemt_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolderingScheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="img/no_scheme.png",
                        height_field="image_height",
                        null=True,
                        upload_to="img/",
                        width_field="image_width",
                    ),
                ),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_soldering_scheme",
                        to="technology.itemt",
                        verbose_name="Номенклатура",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
