# Generated by Django 4.2.23 on 2025-08-10 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0044_solderingscheme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solderingscheme",
            options={
                "ordering": ["item"],
                "verbose_name": "Схема пайки",
                "verbose_name_plural": "Схемы пайки",
            },
        ),
        migrations.AlterModelTable(
            name="solderingscheme",
            table="solderingscheme",
        ),
    ]
