# Generated by Django 4.2.23 on 2025-08-10 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0045_alter_solderingscheme_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SolderingScheme",
        ),
    ]
