# Generated by Django 4.2.23 on 2025-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0047_solderingscheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingscheme",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="identifier"
            ),
        ),
    ]
