# Generated by Django 4.2.23 on 2025-08-11 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0048_alter_solderingscheme_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("barcode", models.CharField(max_length=50)),
                (
                    "label_template",
                    models.CharField(
                        choices=[("standard", "Стандартная"), ("pro", "Расширенная")],
                        max_length=100,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="technology.itemt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этикетка",
                "verbose_name_plural": "Этикетки",
                "db_table": "label",
                "ordering": ["product"],
                "abstract": False,
            },
        ),
    ]
