# Generated by Django 4.2.23 on 2025-08-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0049_productlabel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productlabel",
            options={
                "ordering": ["item"],
                "verbose_name": "Этикетка",
                "verbose_name_plural": "Этикетки",
            },
        ),
        migrations.RemoveField(
            model_name="productlabel",
            name="product",
        ),
        migrations.AddField(
            model_name="productlabel",
            name="item",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="technology.itemt",
            ),
            preserve_default=False,
        ),
    ]
