# Generated by Django 4.2.23 on 2025-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0050_alter_productlabel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productlabel",
            name="id",
        ),
        migrations.AddField(
            model_name="productlabel",
            name="name",
            field=models.CharField(
                default="",
                max_length=300,
                primary_key=True,
                serialize=False,
                verbose_name="name",
            ),
            preserve_default=False,
        ),
    ]
