# Generated by Django 4.2.23 on 2025-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0051_remove_productlabel_id_productlabel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlabel",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="productlabel",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="productlabel",
            name="id",
            field=models.AutoField(
                auto_created=True,
                #default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
