# Generated by Django 4.2.23 on 2025-08-12 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0052_productlabel_id_alter_productlabel_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileHanger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="number")),
                (
                    "current_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tied_hangers",
                        to="technology.itemt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мобильное вешало",
                "verbose_name_plural": "Мобильные вешала",
                "db_table": "hangers",
                "ordering": ["number"],
                "abstract": False,
            },
        ),
    ]
