# Generated by Django 4.2.23 on 2025-08-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0053_mobilehanger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilehanger",
            name="current_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tied_hangers",
                to="technology.itemt",
            ),
        ),
        migrations.AlterField(
            model_name="mobilehanger",
            name="number",
            field=models.IntegerField(verbose_name="Номер"),
        ),
    ]
