# Generated by Django 4.2.23 on 2025-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0054_alter_mobilehanger_current_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilehanger",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="identifier"
            ),
        ),
    ]
