# Generated by Django 4.2.23 on 2025-08-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0055_alter_mobilehanger_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilehanger",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
