# Generated by Django 4.2.23 on 2025-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0056_alter_mobilehanger_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilehanger",
            name="id",
        ),
        migrations.AlterField(
            model_name="mobilehanger",
            name="number",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Номер"
            ),
        ),
    ]
