# Generated by Django 4.2.23 on 2025-08-17 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0057_remove_mobilehanger_id_alter_mobilehanger_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceScheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "hanged_no",
                    models.CharField(
                        blank=True,
                        help_text="Номер крючка на вешале",
                        max_length=20,
                        null=True,
                        verbose_name="№ на вешале",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="img/no_image.png",
                        height_field="image_height",
                        null=True,
                        upload_to="img/",
                        width_field="image_width",
                    ),
                ),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_schemes",
                        to="technology.itemt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема трассировки",
                "verbose_name_plural": "Схемы трассировки",
                "db_table": "trace_list",
                "ordering": ["item"],
                "abstract": False,
            },
        ),
    ]
