# Generated by Django 4.2.23 on 2025-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0058_tracescheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracescheme",
            name="wire_no",
            field=models.CharField(
                default="",
                help_text="Имя жилы или провода",
                max_length=20,
                verbose_name="имя провода",
            ),
            preserve_default=False,
        ),
    ]
