# Generated by Django 4.2.23 on 2025-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0059_tracescheme_wire_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracescheme",
            name="wire_no",
            field=models.CharField(
                blank=True,
                help_text="Имя жилы или провода",
                max_length=20,
                null=True,
                verbose_name="имя провода",
            ),
        ),
    ]
