# Generated by Django 4.2.23 on 2025-08-17 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0060_alter_tracescheme_wire_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracescheme",
            name="wire_no",
        ),
    ]
