# Generated by Django 4.2.23 on 2025-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0062_remove_tracescheme_hanged_no_tracescheme_wire_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilehanger",
            name="number",
            field=models.CharField(
                primary_key=True, serialize=False, verbose_name="Номер"
            ),
        ),
    ]
