# Generated by Django 4.2.23 on 2025-08-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0063_alter_mobilehanger_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilehanger",
            name="number",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Номер"
            ),
        ),
    ]
