# Generated by Django 4.2.23 on 2025-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0064_alter_mobilehanger_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilehanger",
            name="number",
            field=models.IntegerField(verbose_name="Номер"),
        ),
        migrations.AddField(
            model_name="mobilehanger",
            name="id",
            field=models.AutoField(
                auto_created=True,
                #default="0",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
