# Generated by Django 4.2.23 on 2025-08-23 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0066_alter_mobilehanger_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cutlist",
            table="connection_list",
        ),
    ]
