# Generated by Django 4.2.23 on 2025-08-23 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0186_alter_item_latedemandcount_and_more"),
        ("technology", "0067_alter_cutlist_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CutList",
            new_name="ConnectionList",
        ),
        migrations.AlterModelOptions(
            name="connectionlist",
            options={
                "ordering": ["SP_pos"],
                "verbose_name": "Таблица соединений",
                "verbose_name_plural": "Таблицы соединений",
            },
        ),
    ]
