# Generated by Django 4.2.23 on 2025-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0068_rename_cutlist_connectionlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemt",
            name="erp_code",
            field=models.CharField(blank=True, null=True, verbose_name="erp code"),
        ),
    ]
