# Generated by Django 4.2.23 on 2025-10-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0013_mqr"),
        ("technology", "0069_itemt_erp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemt",
            name="qr1",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_owners",
                to="codescan.mqr",
                verbose_name="QR код",
            ),
        ),
    ]
