# Generated by Django 4.2.23 on 2025-10-02 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0070_itemt_qr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemt",
            old_name="qr1",
            new_name="qr",
        ),
    ]
