# Generated by Django 4.2.23 on 2025-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0071_rename_qr1_itemt_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemt",
            name="imagef",
            field=models.ImageField(
                blank=True,
                default="img/no_image_F.png",
                height_field="imagef_height",
                null=True,
                upload_to="img/",
                width_field="imagef_width",
            ),
        ),
        migrations.AlterField(
            model_name="tracescheme",
            name="image",
            field=models.ImageField(
                blank=True,
                default="uploads/img/no_image.png",
                height_field="image_height",
                null=True,
                upload_to="img/",
                width_field="image_width",
            ),
        ),
    ]
