# Generated by Django 4.2.23 on 2025-10-03 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0075_itemt_barcode_itemt_barcode_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemt",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="itemt",
            name="barcode_number",
        ),
    ]
