# Generated by Django 4.2.23 on 2025-10-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0020_barcode"),
        ("technology", "0076_remove_itemt_barcode_remove_itemt_barcode_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemt",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barcode_owners",
                to="codescan.barcode",
                verbose_name="Штрих код",
            ),
        ),
        migrations.AddField(
            model_name="itemt",
            name="barcode_number",
            field=models.CharField(
                blank=True, null=True, verbose_name="Номер штрих-кода"
            ),
        ),
    ]
