# Generated by Django 4.2.23 on 2025-10-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0021_alter_productpassport_status'),
        ('codescan', '0022_alter_codescanevent_user_alter_usercodes_user'),
        ('input', '0236_alter_item_latedemandcount_and_more'),
        ('technology', '0077_itemt_barcode_itemt_barcode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemt',
            name='passport_label_template',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_passports', to='qm.label', verbose_name='Шаблон этикетки паспорта'),
        ),
        migrations.AlterField(
            model_name='connectionlist',
            name='from_seal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_seal_in_cutlists', to='technology.itemt', verbose_name='уплотнитель начала провода'),
        ),
        migrations.AlterField(
            model_name='connectionlist',
            name='from_tip',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_tip_in_cutlists', to='technology.itemt', verbose_name='наконечник начала провода'),
        ),
        migrations.AlterField(
            model_name='connectionlist',
            name='item',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_cutlists', to='technology.itemt', verbose_name='провод'),
        ),
        migrations.AlterField(
            model_name='connectionlist',
            name='operation',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='operation_cutlists', to='input.operation', verbose_name='операция'),
        ),
        migrations.AlterField(
            model_name='connectionlist',
            name='to_seal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_seal_in_cutlists', to='technology.itemt', verbose_name='уплотнитель конец провода'),
        ),
        migrations.AlterField(
            model_name='connectionlist',
            name='to_tip',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_tip_in_cutlists', to='technology.itemt', verbose_name='наконечник конца провода'),
        ),
        migrations.AlterField(
            model_name='itemt',
            name='barcode',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barcode_owners', to='codescan.barcode', verbose_name='Штрих код'),
        ),
        migrations.AlterField(
            model_name='itemt',
            name='qr',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_owners', to='codescan.qr', verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='mobilehanger',
            name='current_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tied_hangers', to='technology.itemt'),
        ),
        migrations.AlterField(
            model_name='solderingscheme',
            name='item',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_soldering_scheme', to='technology.itemt', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='tracescheme',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trace_schemes', to='technology.itemt'),
        ),
        migrations.DeleteModel(
            name='ProductLabel',
        ),
    ]
