# Generated by Django 4.2.23 on 2025-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0078_itemt_passport_label_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionlist',
            name='from_connector',
            field=models.CharField(blank=True, help_text='от разъёма', max_length=20, null=True, verbose_name='от разъёма'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='from_pin',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='от контакта', max_digits=3, null=True, verbose_name='от контакта'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='sygnal',
            field=models.CharField(blank=True, help_text='Имя цепи', max_length=20, null=True, verbose_name='имя цепи'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='to_connector',
            field=models.CharField(blank=True, help_text='к разъёму', max_length=20, null=True, verbose_name='к разъёму'),
        ),
        migrations.AddField(
            model_name='connectionlist',
            name='to_pin',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='к контакту', max_digits=3, null=True, verbose_name='к контакту'),
        ),
    ]
