# Generated by Django 4.2.23 on 2025-10-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0079_connectionlist_from_connector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemt',
            name='opposite_item',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opposite_items', to='technology.itemt', verbose_name='Ответная часть'),
        ),
    ]
