# Generated by Django 4.2.23 on 2025-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0080_itemt_opposite_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracescheme',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field='image_height', null=True, upload_to='img/', width_field='image_width'),
        ),
    ]
