# Generated by Django 4.2.23 on 2025-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0081_alter_tracescheme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemt',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field='image_height', null=True, upload_to='img/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='itemt',
            name='imagef',
            field=models.ImageField(blank=True, default=None, height_field='imagef_height', null=True, upload_to='img/', width_field='imagef_width'),
        ),
    ]
