# Generated by Django 4.2.23 on 2025-10-31 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0080_itemt_opposite_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchConnectors',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('connector_name', models.CharField(blank=True, max_length=50, null=True)),
                ('connector_designation', models.CharField(max_length=10)),
                ('connector_pins_no', models.IntegerField()),
                ('connector', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_testbench_connectors', to='technology.itemt', verbose_name='Разъём стенда')),
            ],
            options={
                'verbose_name': 'Разъём стенда',
                'verbose_name_plural': 'Разъёмы стенда',
                'db_table': 'testbench_connectors',
                'abstract': False,
            },
        ),
    ]
