# Generated by Django 4.2.23 on 2025-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0080_itemt_opposite_item'),
        ('testbench', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchconnectors',
            name='connector',
            field=models.ForeignKey(db_index=False, limit_choices_to={'opposite_item__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='item_testbench_connectors', to='technology.itemt', verbose_name='Разъём стенда'),
        ),
    ]
