# Generated by Django 4.2.23 on 2026-02-22 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testbench', '0001_initial'),
    ]

    operations = [

    ]
