# Generated by Django 4.2.23 on 2026-02-22 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0004_connectionlist_itemt_mobilehanger_solderingscheme_and_more'),
        ('testbench', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchConnectors',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('connector_name', models.CharField(blank=True, max_length=50, null=True)),
                ('connector_designation', models.CharField(max_length=10, unique=True)),
                ('connector_pins_no', models.IntegerField()),
                ('light_led_mqtt_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='MQTT ID светодиода')),
                ('connector', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_testbench_connectors', to='technology.itemt', verbose_name='Разъём стенда')),
            ],
            options={
                'verbose_name': 'Разъём стенда',
                'verbose_name_plural': 'Разъёмы стенда',
                'db_table': 'testbench_connectors',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenchChannels',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('bench_pin_no', models.IntegerField(verbose_name='Контакт разъёма')),
                ('channel', models.IntegerField(verbose_name='Канал тестера')),
                ('bench_connector', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='testbench.benchconnectors', verbose_name='Разъём стенда')),
            ],
            options={
                'verbose_name': 'Подключение стенда',
                'verbose_name_plural': 'Подключения стенда',
                'db_table': 'testbench_channels',
                'abstract': False,
                'unique_together': {('bench_connector', 'bench_pin_no')},
            },
        ),
    ]
