# Generated by Django 4.2.23 on 2025-10-31 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0080_itemt_opposite_item'),
        ('testbench', '0002_alter_benchconnectors_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchconnectors',
            name='connector',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_testbench_connectors', to='technology.itemt', verbose_name='Разъём стенда'),
        ),
        migrations.AlterField(
            model_name='benchconnectors',
            name='connector_designation',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
