# Generated by Django 4.2.23 on 2025-11-08 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testbench', '0003_alter_benchconnectors_connector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchChannels',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('bench_pin_no', models.IntegerField(verbose_name='Контакт разъёма')),
                ('channel', models.IntegerField(verbose_name='Канал тестера')),
                ('bench_connector', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='testbench.benchconnectors', verbose_name='Разъём стенда')),
            ],
            options={
                'verbose_name': 'Подключениt стенда',
                'verbose_name_plural': 'Подключения стенда',
                'db_table': 'testbench_channels',
                'abstract': False,
                'unique_together': {('bench_connector', 'bench_pin_no')},
            },
        ),
    ]
