# Generated by Django 4.2.23 on 2025-11-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testbench', '0004_benchchannels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchchannels',
            options={'verbose_name': 'Подключение стенда', 'verbose_name_plural': 'Подключения стенда'},
        ),
    ]
