# Generated by Django 4.2.23 on 2025-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbench', '0005_alter_benchchannels_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchconnectors',
            name='light_led_mqtt_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MQTT ID светодиода'),
        ),
    ]
