# Generated by Django 4.2.23 on 2025-07-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_alter_attribute_model_alter_comment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="model",
            field=models.CharField(
                choices=[
                    ("calendar", "calendar"),
                    ("supplier", "supplier"),
                    ("item", "item"),
                    ("location", "location"),
                    ("customer", "customer"),
                    ("demand", "demand"),
                    ("operation", "operation"),
                    ("operationplan", "operationplan"),
                    ("operationplanmaterial", "operationplanmaterial"),
                    ("setupmatrix", "setupmatrix"),
                    ("skill", "skill"),
                    ("resource", "resource"),
                    ("operationplanresource", "operationplanresource"),
                    ("suboperation", "suboperation"),
                    ("setuprule", "setuprule"),
                    ("resourceskill", "resourceskill"),
                    ("operationresource", "operationresource"),
                    ("operationmaterial", "operationmaterial"),
                    ("itemsupplier", "itemsupplier"),
                    ("itemdistribution", "itemdistribution"),
                    ("calendarbucket", "calendarbucket"),
                    ("buffer", "buffer"),
                    ("operationdependency", "operationdependency"),
                    ("forecast", "forecast"),
                    ("constraint", "constraint"),
                    ("problem", "problem"),
                    ("user", "user"),
                    ("bucket", "bucket"),
                    ("bucketdetail", "bucketdetail"),
                    ("my_model", "my_model"),
                    ("cutlist", "cutlist"),
                ],
                max_length=300,
                verbose_name="model",
            ),
        ),
    ]
