# Generated by Django 4.2.23 on 2025-10-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0052_alter_attribute_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="model",
            field=models.CharField(
                choices=[
                    ("calendar", "calendar"),
                    ("supplier", "supplier"),
                    ("item", "item"),
                    ("location", "location"),
                    ("customer", "customer"),
                    ("demand", "demand"),
                    ("operation", "operation"),
                    ("operationplan", "operationplan"),
                    ("operationplanmaterial", "operationplanmaterial"),
                    ("setupmatrix", "setupmatrix"),
                    ("skill", "skill"),
                    ("resource", "resource"),
                    ("operationplanresource", "operationplanresource"),
                    ("suboperation", "suboperation"),
                    ("setuprule", "setuprule"),
                    ("resourceskill", "resourceskill"),
                    ("operationresource", "operationresource"),
                    ("operationmaterial", "operationmaterial"),
                    ("itemsupplier", "itemsupplier"),
                    ("itemdistribution", "itemdistribution"),
                    ("calendarbucket", "calendarbucket"),
                    ("buffer", "buffer"),
                    ("operationdependency", "operationdependency"),
                    ("forecast", "forecast"),
                    ("constraint", "constraint"),
                    ("problem", "problem"),
                    ("user", "user"),
                    ("bucket", "bucket"),
                    ("bucketdetail", "bucketdetail"),
                    ("my_model", "my_model"),
                    ("mqrcode", "mqrcode"),
                    ("codestypes", "codestypes"),
                    ("usercodes", "usercodes"),
                    ("codescanevent", "codescanevent"),
                    ("usercodes", "usercodes"),
                    ("codestypes", "codestypes"),
                    ("richitem", "richitem"),
                    ("codescanevent", "codescanevent"),
                    ("lastusedqr", "lastusedqr"),
                    ("itemt", "itemt"),
                    ("workstation", "workstation"),
                    ("solderingscheme", "solderingscheme"),
                    ("productlabel", "productlabel"),
                    ("mobilehanger", "mobilehanger"),
                    ("tracescheme", "tracescheme"),
                    ("connectionlist", "connectionlist"),
                    ("qr", "qr"),
                ],
                max_length=300,
                verbose_name="model",
            ),
        ),
    ]
