# Generated by Django 4.2.23 on 2025-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0081_customer_code_item_code_item_qr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="Заказчик код 1С",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="Номенклатура код 1С",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="qr",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="Номенклатура QR код",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latedemandcount",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="count of late demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latedemandquantity",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="quantity of late demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latedemandvalue",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="value of late demand",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unplanneddemandcount",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="count of unplanned demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unplanneddemandquantity",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="quantity of unplanned demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unplanneddemandvalue",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="value of unplanned demands",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="overloadcount",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="count of capacity overload problems",
            ),
        ),
    ]
