# Generated by Django 4.2.23 on 2026-02-22 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codescan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('barcode', models.CharField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, height_field='image_height', null=True, upload_to='barcode/', width_field='image_width')),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LastUsedQR',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qr', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Last used QR',
                'verbose_name_plural': 'Last used QRs',
                'db_table': 'last_qr',
            },
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('qr', models.CharField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, height_field='image_height', null=True, upload_to='qr/', width_field='image_width')),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='РМ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('qr', models.TextField(verbose_name='qr код')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='codescanevent',
            name='session_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='codescanevent',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='User', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usercodes',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercodes',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='User', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
