# Generated by Django 4.2.23 on 2025-07-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0002_alter_codescanevent_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codescanevent",
            name="session_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
