# Generated by Django 4.2.23 on 2025-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0004_alter_codescanevent_user_alter_usercodes_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercodes",
            name="code",
            field=models.CharField(max_length=100),
        ),
    ]
