# Generated by Django 4.2.23 on 2025-07-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0005_alter_usercodes_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codescanevent",
            name="session_id",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
