# Generated by Django 4.2.23 on 2025-07-30 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0006_alter_codescanevent_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastUsedQR",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("qr", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Last used mQR",
                "verbose_name_plural": "Last used mQRs",
                "db_table": "last_qr",
            },
        ),
    ]
