# Generated by Django 4.2.23 on 2025-07-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0007_lastusedqr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastusedqr",
            name="id",
        ),
        migrations.AlterField(
            model_name="lastusedqr",
            name="model",
            field=models.CharField(
                choices=[
                    ("0", "Оснастка"),
                    ("1", "Мобильное вешало"),
                    ("2", "Рабочее место"),
                    ("3", "Оборудование"),
                    ("4", "Мобильный стеллаж"),
                    ("5", "Стеллаж проводов"),
                    ("6", "Номенклатура"),
                    ("7", "Операция"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="lastusedqr",
            name="qr",
            field=models.CharField(max_length=8),
        ),
    ]
