# Generated by Django 4.2.23 on 2025-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0008_remove_lastusedqr_id_alter_lastusedqr_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastusedqr",
            name="model",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
