# Generated by Django 4.2.23 on 2025-08-03 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0009_alter_lastusedqr_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workstation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название РМ")),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("qr", models.TextField(verbose_name="qr код")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
