# Generated by Django 4.2.23 on 2025-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0010_workstation"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstation",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="РМ"
            ),
        ),
        migrations.AlterField(
            model_name="workstation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
