# Generated by Django 4.2.23 on 2025-08-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0011_workstation_short_name_alter_workstation_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstation",
            name="id",
        ),
        migrations.AlterField(
            model_name="workstation",
            name="name",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Название",
            ),
        ),
    ]
