# Generated by Django 4.2.23 on 2025-10-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0013_mqr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mqr",
            name="id",
        ),
        migrations.AlterField(
            model_name="mqr",
            name="mqr",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
