# Generated by Django 4.2.23 on 2025-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0014_remove_mqr_id_alter_mqr_mqr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mqr",
            name="image",
            field=models.ImageField(
                default="uploads/qr/no_image.png",
                height_field="image_height",
                null=True,
                upload_to="qr/",
                width_field="image_width",
            ),
        ),
    ]
