# Generated by Django 4.2.23 on 2025-10-02 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0015_alter_mqr_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mqr",
            old_name="mqr",
            new_name="qr",
        ),
    ]
