# Generated by Django 4.2.23 on 2025-10-02 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0071_rename_qr1_itemt_qr"),
        ("codescan", "0016_rename_mqr_mqr_qr"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="mQR",
            new_name="QR",
        ),
    ]
