# Generated by Django 4.2.23 on 2025-10-02 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0017_rename_mqr_qr"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lastusedqr",
            options={
                "verbose_name": "Last used QR",
                "verbose_name_plural": "Last used QRs",
            },
        ),
    ]
