# Generated by Django 4.2.23 on 2025-10-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0018_alter_lastusedqr_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr",
            name="image",
            field=models.ImageField(
                default="qr/no_image.png",
                height_field="image_height",
                null=True,
                upload_to="qr/",
                width_field="image_width",
            ),
        ),
    ]
