# Generated by Django 4.2.23 on 2025-10-03 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0019_alter_qr_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="barcode",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("barcode", models.CharField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        default="qr/no_image.png",
                        height_field="image_height",
                        null=True,
                        upload_to="barcode/",
                        width_field="image_width",
                    ),
                ),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
