# Generated by Django 4.2.23 on 2025-10-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codescan", "0020_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="image",
            field=models.ImageField(
                default="img/no_image.png",
                height_field="image_height",
                null=True,
                upload_to="barcode/",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="qr",
            name="image",
            field=models.ImageField(
                default="img/no_image.png",
                height_field="image_height",
                null=True,
                upload_to="qr/",
                width_field="image_width",
            ),
        ),
    ]
