# Generated by Django 4.2.23 on 2025-10-25 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codescan', '0021_alter_barcode_image_alter_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codescanevent',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='User', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usercodes',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='User', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
