# Generated by Django 4.2.23 on 2025-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescan', '0022_alter_codescanevent_user_alter_usercodes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='image',
            field=models.ImageField(default=None, height_field='image_height', null=True, upload_to='barcode/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='image',
            field=models.ImageField(default=None, height_field='image_height', null=True, upload_to='qr/', width_field='image_width'),
        ),
    ]
