# Generated by Django 4.2.23 on 2026-02-22 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='ProductPassport',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('date', models.DateTimeField(auto_now=True)),
                ('serial_number', models.IntegerField(blank=True, verbose_name='s/n')),
                ('label_path', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, default='Создан', max_length=50, null=True)),
                ('part_name', models.CharField(blank=True, max_length=200, null=True)),
                ('firmware', models.CharField(blank=True, max_length=200, null=True)),
                ('specification', models.CharField(blank=True, max_length=200, null=True)),
                ('sertificate', models.CharField(blank=True, max_length=200, null=True)),
                ('sertificate_validto', models.DateTimeField(blank=True, null=True)),
                ('last_maintenance', models.CharField(blank=True, max_length=200, null=True)),
                ('last_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('user_manual', models.URLField(blank=True, null=True)),
                ('service_manual', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('manufacturing_order', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_passports', to='input.manufacturingorder', verbose_name='Заказ в производство')),
                ('product_qrcode', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_passports', to='codescan.qr', verbose_name='QR код продукта')),
            ],
            options={
                'verbose_name': 'Паспорт изделия',
                'verbose_name_plural': 'Паспорта изделий',
                'db_table': 'pasports',
                'abstract': False,
                'unique_together': {('manufacturing_order', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='SerialUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('last_serial', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Last used serial',
                'verbose_name_plural': 'Last used serialss',
                'db_table': 'last_serials',
            },
        ),
        migrations.CreateModel(
            name='QualityControlTypes',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('type', models.CharField(choices=[('прозвонка', 'Continuity'), ('визуальный контроль', 'Visual'), ('климатические испытания', 'Climate')], default='прозвонка', max_length=200)),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='qm_control_types', to='technology.itemt', verbose_name='Объект контроля')),
            ],
            options={
                'verbose_name': 'Требование контроля качества',
                'verbose_name_plural': 'Требования контроля качества',
                'db_table': 'qm_quality_control_types',
                'abstract': False,
                'unique_together': {('item', 'type')},
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('date', models.DateTimeField(auto_now=True)),
                ('control_result', models.CharField(blank=True, max_length=50, null=True)),
                ('control_result_log', models.JSONField(blank=True, default=dict, help_text='Отчёт по результатам контроля', null=True)),
                ('product_passport', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='quality_control_results', to='qm.productpassport', verbose_name='Паспорт продукта')),
                ('type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='type_quality_controls', to='qm.qualitycontroltypes', verbose_name='Вид контроля')),
            ],
            options={
                'verbose_name': 'Контроль качества',
                'verbose_name_plural': 'Контроль качества',
                'db_table': 'qm_quality_control',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('serie_no_start', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Начальный s/n')),
                ('serials_created', models.BooleanField(blank=True, default=False, verbose_name='s/n созданы')),
                ('manufacturing_order', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_batch', to='input.manufacturingorder', verbose_name='Заказ в производство')),
            ],
            options={
                'verbose_name': 'Серия номенклатуры',
                'verbose_name_plural': 'Серии номенклатуры',
                'db_table': 'batch_list',
                'ordering': ['id', 'serie_no_start'],
                'abstract': False,
            },
        ),
    ]
