# Generated by Django 4.2.23 on 2025-10-06 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("input", "0218_alter_item_latedemandcount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchList",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="identifier"
                    ),
                ),
                (
                    "serie_no_start",
                    models.DecimalField(
                        decimal_places=0,
                        default="",
                        max_digits=20,
                        verbose_name="Начальный s/n",
                    ),
                ),
                (
                    "manufacturing_order",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_batch",
                        to="input.manufacturingorder",
                        verbose_name="Заказ в производство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серия номенклатуры",
                "verbose_name_plural": "Серии номенклатуры",
                "db_table": "batch_list",
                "ordering": ["id", "serie_no_start"],
                "abstract": False,
            },
        ),
    ]
