# Generated by Django 4.2.23 on 2026-02-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='qm_batch_list',
        ),
        migrations.AlterModelTable(
            name='productpassport',
            table='qm_pasports',
        ),
        migrations.AlterModelTable(
            name='serialused',
            table='qm_last_serials',
        ),
    ]
