# Generated by Django 4.2.23 on 2025-10-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0219_alter_item_latedemandcount_and_more"),
        ("qm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchlist",
            name="manufacturing_order",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_batch",
                to="input.manufacturingorder",
                unique=True,
                verbose_name="Заказ в производство",
            ),
        ),
    ]
