# Generated by Django 4.2.23 on 2026-02-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_createdlabel'),
        ('qm', '0002_alter_batch_table_alter_productpassport_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpassport',
            name='label',
            field=models.ForeignKey(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_passports', to='labels.createdlabel', verbose_name='Этикетка'),
        ),
    ]
