# Generated by Django 4.2.23 on 2025-10-12 21:12

from django.db import migrations, models
import django.utils.timezone
import freppledb.qm.models


class Migration(migrations.Migration):
    dependencies = [
        ("qm", "0002_alter_batchlist_manufacturing_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="name")),
                ("barcode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "template",
                    models.FileField(
                        upload_to="svg/",
                        validators=[freppledb.qm.models.Label.validate_svg],
                    ),
                ),
            ],
            options={
                "verbose_name": "Этикетка",
                "verbose_name_plural": "Этикетки",
                "db_table": "labels",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SerialUsed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                ("last_serial", models.IntegerField(max_length=8)),
            ],
            options={
                "verbose_name": "Last used serial",
                "verbose_name_plural": "Last used serialss",
                "db_table": "last_serials",
            },
        ),
        migrations.AlterField(
            model_name="batchlist",
            name="serie_no_start",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="Начальный s/n"
            ),
        ),
    ]
