# Generated by Django 4.2.23 on 2026-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0003_productpassport_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpassport',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
