# Generated by Django 4.2.23 on 2025-10-16 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0220_alter_item_latedemandcount_and_more'),
        ('codescan', '0021_alter_barcode_image_alter_qr_image'),
        ('qm', '0003_label_serialused_alter_batchlist_serie_no_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchList',
            new_name='Batch',
        ),
        migrations.CreateModel(
            name='ProductPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('date', models.DateTimeField(auto_now=True)),
                ('manufacturing_order', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_passports', to='input.manufacturingorder', unique=True, verbose_name='Заказ в производство')),
                ('qrcode', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_passports', to='codescan.qr', unique=True, verbose_name='QR код')),
            ],
            options={
                'verbose_name': 'Паспорт качества',
                'verbose_name_plural': 'Паспортв качества',
                'db_table': 'pasports',
                'abstract': False,
            },
        ),
    ]
