# Generated by Django 4.2.23 on 2025-10-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0004_rename_batchlist_batch_productpassport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Шаблон этикетки', 'verbose_name_plural': 'Шаблоны этикеток'},
        ),
        migrations.AlterModelOptions(
            name='productpassport',
            options={'verbose_name': 'Паспорт bpltkbz', 'verbose_name_plural': 'Паспортв bpltkbq'},
        ),
        migrations.AddField(
            model_name='productpassport',
            name='serial_number',
            field=models.CharField(blank=True, verbose_name='s/n'),
        ),
        migrations.AlterField(
            model_name='productpassport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
