# Generated by Django 4.2.23 on 2025-10-19 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codescan', '0021_alter_barcode_image_alter_qr_image'),
        ('technology', '0077_itemt_barcode_itemt_barcode_number'),
        ('qm', '0005_alter_label_options_alter_productpassport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpassport',
            options={'verbose_name': 'Паспорт изделия', 'verbose_name_plural': 'Паспорта изделий'},
        ),
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='item_product_labels', to='technology.itemt', verbose_name='Продукт')),
                ('label_template', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='label_products', to='qm.label', verbose_name='Шаблон этикетки')),
                ('passport', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='passport_labels', to='qm.productpassport', verbose_name='Паспорт продукта')),
                ('qrcode', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_labels', to='codescan.qr', unique=True, verbose_name='QR код продукта')),
            ],
            options={
                'verbose_name': 'Этикетка изделия',
                'verbose_name_plural': 'Этикетки изделий',
                'db_table': 'product_labels',
                'abstract': False,
            },
        ),
    ]
