# Generated by Django 4.2.23 on 2025-10-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0077_itemt_barcode_itemt_barcode_number'),
        ('codescan', '0021_alter_barcode_image_alter_qr_image'),
        ('qm', '0006_alter_productpassport_options_productlabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpassport',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='productpassport',
            name='product',
            field=models.ForeignKey(db_index=False, default='', on_delete=django.db.models.deletion.CASCADE, related_name='item_product_labels', to='technology.itemt', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpassport',
            name='product_qrcode',
            field=models.ForeignKey(db_index=False, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_passports', to='codescan.qr', unique=True, verbose_name='QR код продукта'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductLabel',
        ),
    ]
