# Generated by Django 4.2.23 on 2025-10-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0221_alter_item_latedemandcount_and_more'),
        ('codescan', '0021_alter_barcode_image_alter_qr_image'),
        ('qm', '0007_remove_productpassport_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='manufacturing_order',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_batch', to='input.manufacturingorder', verbose_name='Заказ в производство'),
        ),
        migrations.AlterField(
            model_name='productpassport',
            name='manufacturing_order',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_passports', to='input.manufacturingorder', verbose_name='Заказ в производство'),
        ),
        migrations.AlterField(
            model_name='productpassport',
            name='product_qrcode',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_passports', to='codescan.qr', verbose_name='QR код продукта'),
        ),
        migrations.AlterField(
            model_name='serialused',
            name='last_serial',
            field=models.IntegerField(),
        ),
    ]
