# Generated by Django 4.2.23 on 2025-10-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0008_alter_batch_manufacturing_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpassport',
            name='serial_number',
            field=models.IntegerField(blank=True, verbose_name='s/n'),
        ),
    ]
