# Generated by Django 4.2.23 on 2025-10-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0222_alter_item_latedemandcount_and_more'),
        ('qm', '0009_alter_productpassport_serial_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpassport',
            unique_together={('manufacturing_order', 'serial_number')},
        ),
    ]
