# Generated by Django 4.2.23 on 2025-10-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0224_alter_item_latedemandcount_and_more'),
        ('qm', '0010_alter_productpassport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpassport',
            name='manufacturing_order',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_passports', to='input.manufacturingorder', verbose_name='Заказ в производство'),
        ),
    ]
