# Generated by Django 4.2.23 on 2025-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0013_alter_productpassport_manufacturing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='serials_created',
            field=models.BooleanField(blank=True, default=False, verbose_name='s/n созданы'),
        ),
    ]
