# Generated by Django 4.2.23 on 2025-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0014_batch_serials_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpassport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
