# Generated by Django 4.2.23 on 2025-10-22 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0015_productpassport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpassport',
            name='firmware',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='last_maintenance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='part_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='sertificate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='sertificate_validto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='service_manual',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='specification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpassport',
            name='user_manual',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('date', models.DateTimeField(auto_now=True)),
                ('control_result', models.CharField(blank=True, max_length=50, null=True)),
                ('control_result_log', models.JSONField(blank=True, default=dict, help_text='Отчёт по результатам контроля', null=True)),
                ('product_passport', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='quality_control_results', to='qm.productpassport', verbose_name='Паспорт продукта')),
            ],
            options={
                'verbose_name': 'Контроль качества',
                'verbose_name_plural': 'Контроль качества',
                'db_table': 'qm_quality_control',
                'abstract': False,
            },
        ),
    ]
