# Generated by Django 4.2.23 on 2025-10-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0016_productpassport_firmware_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpassport',
            name='product',
        ),
    ]
