# Generated by Django 4.2.23 on 2025-10-23 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0077_itemt_barcode_itemt_barcode_number'),
        ('input', '0233_alter_item_latedemandcount_and_more'),
        ('codescan', '0021_alter_barcode_image_alter_qr_image'),
        ('qm', '0017_remove_productpassport_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='type',
            field=models.ForeignKey(db_index=False, default='', on_delete=django.db.models.deletion.PROTECT, related_name='type_quality_controls', to='qm.productpassport', verbose_name='Вид контроля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='manufacturing_order',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_batch', to='input.manufacturingorder', verbose_name='Заказ в производство'),
        ),
        migrations.AlterField(
            model_name='productpassport',
            name='manufacturing_order',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_passports', to='input.manufacturingorder', verbose_name='Заказ в производство'),
        ),
        migrations.AlterField(
            model_name='productpassport',
            name='product_qrcode',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_passports', to='codescan.qr', verbose_name='QR код продукта'),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='product_passport',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='quality_control_results', to='qm.productpassport', verbose_name='Паспорт продукта'),
        ),
        migrations.CreateModel(
            name='QualityControlTypes',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('type', models.CharField(max_length=200)),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='qm_control_types', to='technology.itemt', verbose_name='Объект контроля')),
            ],
            options={
                'verbose_name': 'Требование контроля качества',
                'verbose_name_plural': 'Требования контроля качества',
                'db_table': 'qm_quality_control_types',
                'abstract': False,
            },
        ),
    ]
