# Generated by Django 4.2.23 on 2025-10-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0077_itemt_barcode_itemt_barcode_number'),
        ('qm', '0018_qualitycontrol_type_alter_batch_manufacturing_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualitycontroltypes',
            unique_together={('item', 'type')},
        ),
    ]
