# Generated by Django 4.2.23 on 2025-10-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0019_alter_qualitycontroltypes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='type_quality_controls', to='qm.qualitycontroltypes', verbose_name='Вид контроля'),
        ),
    ]
