# Generated by Django 4.2.23 on 2025-10-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0020_alter_qualitycontrol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpassport',
            name='status',
            field=models.CharField(blank=True, default='Создан', max_length=50, null=True),
        ),
    ]
