# Generated by Django 4.2.23 on 2025-10-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0021_alter_productpassport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='barcode',
        ),
    ]
