# Generated by Django 4.2.23 on 2025-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0022_remove_label_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpassport',
            name='label_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
