# Generated by Django 4.2.23 on 2025-10-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0023_productpassport_label_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpassport',
            old_name='label_url',
            new_name='label_patch',
        ),
    ]
