# Generated by Django 4.2.23 on 2025-10-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0024_rename_label_url_productpassport_label_patch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpassport',
            old_name='label_patch',
            new_name='label_path',
        ),
    ]
