# Generated by Django 4.2.23 on 2025-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0025_rename_label_patch_productpassport_label_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontroltypes',
            name='type',
            field=models.CharField(choices=[('continuity', 'прозвонка'), ('visual inspaction', 'визуальный контроль'), ('climate inspection', 'климатические испытания')], default='continuity', max_length=200),
        ),
    ]
