# Generated by Django 4.2.23 on 2025-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qm', '0026_alter_qualitycontroltypes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontroltypes',
            name='type',
            field=models.CharField(choices=[('прозвонка', 'Continuity'), ('визуальный контроль', 'Visual'), ('климатические испытания', 'Climate')], default='прозвонка', max_length=200),
        ),
    ]
